Bitrise workflow updates

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,61 +3,77 @@ format_version: '8'
 default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
 project_type: android
 trigger_map:
-  - push_branch: '*'
-    workflow: primary
-  - pull_request_source_branch: '*'
-    workflow: primary
+- push_branch: '*'
+  workflow: primary
+- pull_request_source_branch: '*'
+  workflow: primary
+app:
+  envs:
+  - opts:
+      is_expand: false
+    PROJECT_LOCATION: .
+  - opts:
+      is_expand: false
+    MODULE: app
+  - opts:
+      is_expand: false
+    VARIANT: ''
+  - opts:
+      is_expand: false
+    GRADLEW_PATH: ./gradlew
 workflows:
   primary:
     steps:
-      - activate-ssh-key@4:
-          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-      - git-clone@4: {}
-      - cache-pull@2: {}
-      - script@1:
-          title: Do anything with Script step
-      - install-missing-android-tools@2:
-          inputs:
-            - gradlew_path: $PROJECT_LOCATION/gradlew
-      - android-lint@0:
-          inputs:
-            - project_location: $PROJECT_LOCATION
-            - module: app
-            - variant: debug
-      - android-unit-test@1:
-          inputs:
-            - project_location: $PROJECT_LOCATION
-            - module: app
-            - arguments: ''
-            - variant: debug
-      - android-build-for-ui-testing@0:
-          inputs:
-            - variant: debug
-            - module: app
-      - virtual-device-testing-for-android@1:
-          inputs:
-            - test_type: instrumentation
-            - directories_to_pull: /sdcard/
-            - download_test_results: 'true'
-            - environment_variables: |-
-                coverage=true
-                coverageFile=/sdcard/coverage.ec
-            - test_devices: 'NexusLowRes,29,en,portrait'
-      - script@1:
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                set -e
-                # debug log
-                set -x
+    - activate-ssh-key@4:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@4: {}
+    - cache-pull@2: {}
+    - script@1:
+        title: Do anything with Script step
+    - install-missing-android-tools@2:
+        inputs:
+        - gradlew_path: $PROJECT_LOCATION/gradlew
+    - android-lint@0:
+        inputs:
+        - project_location: $PROJECT_LOCATION
+        - module: app
+        - cache_level: all
+        - variant: debug
+    - android-unit-test@1:
+        inputs:
+        - project_location: $PROJECT_LOCATION
+        - module: app
+        - arguments: ''
+        - cache_level: all
+        - variant: debug
+    - android-build-for-ui-testing@0:
+        inputs:
+        - variant: debug
+        - module: app
+    - virtual-device-testing-for-android@1:
+        inputs:
+        - test_type: instrumentation
+        - directories_to_pull: /sdcard/
+        - download_test_results: 'true'
+        - environment_variables: |-
+            coverage=true
+            coverageFile=/sdcard/coverage.ec
+        - test_devices: 'NexusLowRes,29,en,portrait'
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
 
-                ls -al $VDTESTING_DOWNLOADED_FILES_DIR
-                echo $VDTESTING_DOWNLOADED_FILES_DIR
-      - deploy-to-bitrise-io@1:
-          inputs:
-            - notify_user_groups: none
-      - cache-push@2: {}
+            ls -al $VDTESTING_DOWNLOADED_FILES_DIR
+            echo $VDTESTING_DOWNLOADED_FILES_DIR
+    - deploy-to-bitrise-io@1:
+        inputs:
+        - notify_user_groups: none
+    - cache-push@2: {}
   deploy:
     description: >
       ## How to get a signed APK
@@ -112,90 +128,37 @@ workflows:
       The next change in your repository that matches any of your trigger map
       event will start **deploy** workflow.
     steps:
-      - activate-ssh-key@4:
-          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-      - git-clone@4: {}
-      - cache-pull@2: {}
-      - script@1:
-          title: Do anything with Script step
-      - install-missing-android-tools@2:
-          inputs:
-            - gradlew_path: $PROJECT_LOCATION/gradlew
-      - change-android-versioncode-and-versionname@1:
-          inputs:
-            - build_gradle_path: $PROJECT_LOCATION/$MODULE/build.gradle
-      - android-lint@0:
-          inputs:
-            - project_location: $PROJECT_LOCATION
-            - module: $MODULE
-            - variant: $VARIANT
-      - android-unit-test@1:
-          inputs:
-            - project_location: $PROJECT_LOCATION
-            - module: $MODULE
-            - variant: $VARIANT
-      - android-build@0:
-          inputs:
-            - project_location: $PROJECT_LOCATION
-            - module: $MODULE
-            - build_type: aab
-            - variant: release
-      - sign-apk@1:
-          run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
-      - deploy-to-bitrise-io@1:
-          inputs:
-            - notify_user_groups: none
-      - cache-push@2: {}
-  primary_demo_gradle:
-    steps:
-      - activate-ssh-key@4:
-          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-      - git-clone@4: {}
-      - cache-pull@2: {}
-      - script@1:
-          title: Do anything with Script step
-      - install-missing-android-tools@2:
-          inputs:
-            - gradlew_path: $PROJECT_LOCATION/gradlew
-      - gradle-runner@1:
-          inputs:
-            - gradle_options: ''
-            - gradle_task: lintDebug testDebugUnitTest assembleDebug assembleDebugAndroidTest
-      - virtual-device-testing-for-android@1:
-          inputs:
-            - test_type: instrumentation
-            - directories_to_pull: /sdcard/
-            - download_test_results: 'true'
-            - environment_variables: |-
-                coverage=true
-                coverageFile=/sdcard/coverage.ec
-            - test_devices: 'NexusLowRes,29,en,portrait'
-      - script@1:
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                set -e
-                # debug log
-                set -x
-
-                ls -al $VDTESTING_DOWNLOADED_FILES_DIR
-                echo $VDTESTING_DOWNLOADED_FILES_DIR
-      - deploy-to-bitrise-io@1:
-          inputs:
-            - notify_user_groups: none
-      - cache-push@2: {}
-app:
-  envs:
-    - opts:
-        is_expand: false
-      PROJECT_LOCATION: .
-    - opts:
-        is_expand: false
-      MODULE: app
-    - opts:
-        is_expand: false
-      VARIANT: ''
-    - opts:
-        is_expand: false
-      GRADLEW_PATH: ./gradlew
+    - activate-ssh-key@4:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@4: {}
+    - cache-pull@2: {}
+    - script@1:
+        title: Do anything with Script step
+    - install-missing-android-tools@2:
+        inputs:
+        - gradlew_path: $PROJECT_LOCATION/gradlew
+    - change-android-versioncode-and-versionname@1:
+        inputs:
+        - build_gradle_path: $PROJECT_LOCATION/$MODULE/build.gradle
+    - android-lint@0:
+        inputs:
+        - project_location: $PROJECT_LOCATION
+        - module: $MODULE
+        - variant: $VARIANT
+    - android-unit-test@1:
+        inputs:
+        - project_location: $PROJECT_LOCATION
+        - module: $MODULE
+        - variant: $VARIANT
+    - android-build@0:
+        inputs:
+        - project_location: $PROJECT_LOCATION
+        - module: $MODULE
+        - build_type: aab
+        - variant: release
+    - sign-apk@1:
+        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
+    - deploy-to-bitrise-io@1:
+        inputs:
+        - notify_user_groups: none
+    - cache-push@2: {}
